# Generated by Django 5.2.4 on 2025-09-22 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/additional_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SustainableDevelopmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('agenda', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('NEEDS_BASED', 'Needs Based'), ('RESEARCH_BASED', 'Research Based')], max_length=20)),
                ('estimated_events', models.PositiveIntegerField()),
                ('estimated_trainees', models.PositiveIntegerField()),
                ('primary_beneficiary', models.CharField(max_length=255)),
                ('primary_location', models.CharField(max_length=255)),
                ('logistics_type', models.CharField(choices=[('BOTH', 'Both'), ('EXTERNAL', 'External'), ('INTERNAL', 'Internal')], max_length=10)),
                ('internal_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('external_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sponsor_name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('proposal_document', models.FileField(upload_to='projects/proposals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('providers', models.ManyToManyField(related_name='member_projects', to=settings.AUTH_USER_MODEL)),
                ('additional_documents', models.ManyToManyField(blank=True, related_name='projects', to='projects.projectdocument')),
                ('sdgs', models.ManyToManyField(related_name='projects', to='projects.sustainabledevelopmentgoal')),
            ],
        ),
    ]
