# Generated by Django 5.2.4 on 2025-09-27 10:18

import shared.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('agenda', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('NEEDS_BASED', 'Needs Based'), ('RESEARCH_BASED', 'Research Based')], max_length=20)),
                ('estimated_events', models.PositiveIntegerField()),
                ('estimated_trainees', models.PositiveIntegerField()),
                ('primary_beneficiary', models.CharField(max_length=255)),
                ('primary_location', models.CharField(max_length=255)),
                ('logistics_type', models.CharField(choices=[('BOTH', 'Both'), ('EXTERNAL', 'External'), ('INTERNAL', 'Internal')], max_length=10)),
                ('internal_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('external_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=shared.projects.models.project_document_upload_to)),
                ('document_type', models.CharField(choices=[('PROPOSAL', 'Proposal'), ('ADDITIONAL', 'Additional')], max_length=12)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SustainableDevelopmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
