# Generated by Django 5.2.6 on 2025-11-03 17:09

import django.db.models.deletion
import shared.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_thumbnails/')),
                ('file', models.FileField(upload_to=shared.projects.models.project_document_upload_to)),
                ('document_type', models.CharField(choices=[('PROPOSAL', 'Proposal'), ('ADDITIONAL', 'Additional')], max_length=12)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shared.projects.models.project_event_image_upload_to)),
                ('placeholder', models.BooleanField(default=False)),
                ('has_submission', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('viewed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SustainableDevelopmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('NEEDS_BASED', 'Needs Based'), ('RESEARCH_BASED', 'Research Based')], max_length=20)),
                ('estimated_events', models.PositiveIntegerField()),
                ('event_progress', models.PositiveIntegerField(default=0)),
                ('estimated_trainees', models.PositiveIntegerField()),
                ('total_trained_individuals', models.PositiveIntegerField(default=0)),
                ('primary_beneficiary', models.CharField(max_length=255)),
                ('primary_location', models.CharField(max_length=255)),
                ('logistics_type', models.CharField(choices=[('BOTH', 'Both'), ('EXTERNAL', 'External'), ('INTERNAL', 'Internal')], max_length=10)),
                ('internal_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('external_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('used_budget', models.DecimalField(decimal_places=2, default=0, help_text='Amount of the budget that has been spent.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('has_final_submission', models.BooleanField(default=False, help_text='True when a final submission type has been approved')),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='agenda.agenda')),
            ],
        ),
    ]
