# Generated by Django 5.2.4 on 2025-09-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='campus',
        ),
    ]
