# Generated by Django 5.2.6 on 2025-11-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_agenda_options_agenda_agenda_created_idx_and_more'),
        ('projects', '0002_initial'),
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevent',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'start_date'], name='proj_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'estimated_end_date', 'has_final_submission'], name='proj_completion_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='proj_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_leader', 'status'], name='proj_leader_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['agenda', 'status'], name='proj_agenda_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'document_type', 'uploaded_at'], name='project_docs_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'uploaded_at'], name='project_docs_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['document_type', 'uploaded_at'], name='docs_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['project', '-created_at'], name='proj_eval_proj_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['evaluated_by', '-created_at'], name='proj_eval_user_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['project', 'rating'], name='proj_eval_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['status', 'datetime'], name='proj_evt_sched_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['project', '-datetime', '-created_at'], name='proj_evt_timeline_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['project', 'status', '-datetime'], name='proj_evt_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['-datetime'], name='proj_evt_datetime_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['placeholder', '-datetime'], name='proj_evt_placeholder_idx'),
        ),
        migrations.AddIndex(
            model_name='projectupdate',
            index=models.Index(fields=['user', 'viewed', '-updated_at'], name='proj_upd_user_view_idx'),
        ),
        migrations.AddIndex(
            model_name='projectupdate',
            index=models.Index(fields=['project', '-updated_at'], name='proj_upd_proj_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sustainabledevelopmentgoal',
            index=models.Index(fields=['goal_number'], name='sdg_goal_number_idx'),
        ),
    ]
