# Generated by Django 5.2.6 on 2025-10-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_used_budget_if_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevaluation',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
