# Generated by Django 5.2.4 on 2025-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnails/'),
        ),
    ]
