# Generated by Django 5.2.4 on 2025-09-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='internal_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
