# Generated by Django 5.2.6 on 2025-11-05 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_project_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('expense_date', models.DateField()),
                ('receipt_img', models.ImageField(blank=True, null=True, upload_to='project_expense_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_expenses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_expenses', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', '-expense_date'], name='proj_exp_proj_date_idx'), models.Index(fields=['-expense_date'], name='proj_exp_date_idx')],
            },
        ),
    ]
