# Generated by Django 5.2.6 on 2025-10-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectevaluation_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_final_submission',
            field=models.BooleanField(default=False, help_text='True when a final submission type has been approved'),
        ),
    ]
