# Generated by Django 5.2.4 on 2025-09-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectevaluation',
            name='edited_at',
        ),
    ]
