# Generated by Django 5.2.4 on 2025-10-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequest',
            name='related_docs',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='letter_of_intent',
            field=models.FileField(blank=True, null=True, upload_to='client_requests/letters_of_intent/'),
        ),
        migrations.DeleteModel(
            name='RelatedDocument',
        ),
    ]
