# Generated by Django 5.2.6 on 2025-11-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientrequest',
            options={'verbose_name': 'Client Request', 'verbose_name_plural': 'Client Requests'},
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['status', '-submitted_at'], name='req_status_submit_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['submitted_by', '-submitted_at'], name='req_submitter_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['status', 'reviewed_by'], name='req_review_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['status', 'endorsed_at'], name='req_endorsed_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['submitted_at'], name='req_submitted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['updated_at', 'status'], name='req_updated_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientrequest',
            index=models.Index(fields=['organization'], name='req_org_idx'),
        ),
        migrations.AddIndex(
            model_name='requestupdate',
            index=models.Index(fields=['user', '-updated_at'], name='req_upd_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='requestupdate',
            index=models.Index(fields=['user', 'request', 'viewed'], name='req_upd_unread_idx'),
        ),
    ]
