# Generated by Django 5.2.4 on 2025-10-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_clientrequest_endorsed_at_clientrequest_endorsed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
