# Generated by Django 5.2.4 on 2025-10-12 00:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_requestupdateview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestUpdateView',
            new_name='RequestUpdate',
        ),
    ]
