# Generated by Django 5.2.6 on 2025-11-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(help_text="The unique identifier for the setting (e.g., 'site_name')", max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True, help_text='The value of the setting.')),
                ('description', models.CharField(blank=True, help_text='A brief description of what this setting does.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
            },
        ),
    ]
