# Generated by Django 5.2.6 on 2025-11-02 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_projectevent_status_and_more'),
        ('users', '0002_alter_user_options_remove_user_campus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=10, unique=True)),
                ('total_available', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Annual Budget Pools',
                'unique_together': {('fiscal_year',)},
            },
        ),
        migrations.CreateModel(
            name='CollegeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assigned', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_budget_assignments', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.college')),
            ],
            options={
                'verbose_name': 'College Budget Allocation',
            },
        ),
        migrations.CreateModel(
            name='ExternalFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=200)),
                ('sponsor_contact', models.CharField(blank=True, max_length=200)),
                ('amount_offered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('proposal_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ALLOCATED', 'Budget Allocated'), ('SPENT', 'Budget Spent'), ('ADJUSTED', 'Budget Adjusted')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('college_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.collegebudget')),
                ('external_funding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.externalfunding')),
            ],
            options={
                'verbose_name_plural': 'Budget History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='collegebudget',
            index=models.Index(fields=['college', 'status', 'fiscal_year'], name='colbud_col_stat_yr_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collegebudget',
            unique_together={('college', 'fiscal_year')},
        ),
        migrations.AddIndex(
            model_name='externalfunding',
            index=models.Index(fields=['project', 'status'], name='extfund_proj_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfunding',
            index=models.Index(fields=['status', '-proposal_date'], name='extfund_stat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['college_budget', '-timestamp'], name='budhist_colbud_time_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['external_funding', '-timestamp'], name='budhist_fund_time_idx'),
        ),
    ]
