# Generated by Django 5.2.6 on 2025-10-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assigned', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_remaining', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quarter', models.CharField(max_length=10)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Budget Categories',
            },
        ),
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ALLOCATED', 'Budget Allocated'), ('SPENT', 'Budget Spent'), ('RETURNED', 'Budget Returned'), ('ADJUSTED', 'Budget Adjusted'), ('TRANSFERRED', 'Budget Transferred')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Budget History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=10)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('total_available', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Budget Pools',
            },
        ),
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VP', 'Vice President'), ('DIRECTOR', 'Director'), ('UESO', 'UESO'), ('PROGRAM_HEAD', 'Program Head'), ('DEAN', 'Dean'), ('COORDINATOR', 'Coordinator')], max_length=20, unique=True)),
                ('template_name', models.CharField(max_length=100)),
                ('template_path', models.CharField(max_length=200)),
                ('show_overall_budget', models.BooleanField(default=True)),
                ('show_historical_summary', models.BooleanField(default=True)),
                ('show_detailed_view', models.BooleanField(default=True)),
                ('show_external_funding', models.BooleanField(default=True)),
                ('show_history', models.BooleanField(default=True)),
                ('custom_sections', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=200)),
                ('sponsor_contact', models.CharField(blank=True, max_length=200)),
                ('amount_offered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('proposal_date', models.DateField()),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
