# Generated by Django 5.2.6 on 2025-11-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
        ('projects', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['college', 'status', 'fiscal_year'], name='budalloc_col_stat_yr_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['college', 'quarter'], name='budalloc_col_qtr_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['project', 'status'], name='budalloc_proj_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['category', 'fiscal_year'], name='budalloc_cat_yr_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['status', 'fiscal_year', 'quarter'], name='budalloc_stat_period_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['-created_at'], name='budalloc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['status', 'total_remaining'], name='budalloc_remaining_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['budget_allocation', '-timestamp'], name='budhist_alloc_time_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['external_funding', '-timestamp'], name='budhist_fund_time_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['action', '-timestamp'], name='budhist_action_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['user', '-timestamp'], name='budhist_user_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['-timestamp'], name='budhist_time_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetpool',
            index=models.Index(fields=['fiscal_year', 'quarter'], name='budpool_year_qtr_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetpool',
            index=models.Index(fields=['-created_at'], name='budpool_created_idx'),
        ),
        migrations.AddIndex(
            model_name='budgettemplate',
            index=models.Index(fields=['is_active', 'role'], name='budtmpl_active_role_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfunding',
            index=models.Index(fields=['project', 'status'], name='extfund_proj_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfunding',
            index=models.Index(fields=['status', '-proposal_date'], name='extfund_stat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfunding',
            index=models.Index(fields=['sponsor_name'], name='extfund_sponsor_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfunding',
            index=models.Index(fields=['proposal_date'], name='extfund_proposal_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfunding',
            index=models.Index(fields=['expected_completion', 'status'], name='extfund_complete_idx'),
        ),
    ]
