# Generated by Django 5.2.6 on 2025-10-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('for_product_production', models.BooleanField(default=False)),
                ('for_research', models.BooleanField(default=False)),
                ('for_extension', models.BooleanField(default=False)),
                ('num_trained_individuals', models.PositiveIntegerField(blank=True, null=True)),
                ('image_event', models.ImageField(blank=True, null=True, upload_to='submissions/event_images/')),
                ('image_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
