# Generated by Django 5.2.6 on 2025-10-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/files/')),
                ('for_product_production', models.BooleanField(default=False)),
                ('for_research', models.BooleanField(default=False)),
                ('for_extension', models.BooleanField(default=False)),
                ('num_trained_individuals', models.PositiveIntegerField(blank=True, null=True)),
                ('image_event', models.ImageField(blank=True, null=True, upload_to='submissions/event_images/')),
                ('image_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('REVISION_REQUESTED', 'Revision Requested'), ('FORWARDED', 'Forwarded to UESO'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reason_for_revision', models.TextField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('reason_for_rejection', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('viewed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
