# Generated by Django 5.2.4 on 2025-10-06 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downloadables', '0003_downloadable_is_submission_template_and_more'),
        ('projects', '0003_alter_projectevent_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submission_requirements', to=settings.AUTH_USER_MODEL)),
                ('downloadables', models.ManyToManyField(related_name='submission_requirements', to='downloadables.downloadable')),
                ('projects', models.ManyToManyField(related_name='submission_requirements', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submission_requirements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('for_product_production', models.BooleanField(default=False)),
                ('for_research', models.BooleanField(default=False)),
                ('for_extension', models.BooleanField(default=False)),
                ('num_trained_individuals', models.PositiveIntegerField(blank=True, null=True)),
                ('image_event', models.ImageField(blank=True, null=True, upload_to='submissions/event_images/')),
                ('image_description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_responses', to='projects.projectevent')),
                ('files', models.ManyToManyField(related_name='submission_responses', to='downloadables.downloadable')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='submissions.submissionrequirement')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_submission_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
