# Generated by Django 5.2.4 on 2025-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionrequirement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=32),
        ),
    ]
