# Generated by Django 5.2.6 on 2025-10-15 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downloadables', '0002_initial'),
        ('projects', '0002_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionrequirement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submission_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionrequirement',
            name='downloadables',
            field=models.ManyToManyField(related_name='submission_requirements', to='downloadables.downloadable'),
        ),
        migrations.AddField(
            model_name='submissionrequirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_requirements', to='projects.project'),
        ),
        migrations.AddField(
            model_name='submissionrequirement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submission_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionresponse',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_responses', to='projects.projectevent'),
        ),
        migrations.AddField(
            model_name='submissionresponse',
            name='files',
            field=models.ManyToManyField(related_name='submission_responses', to='downloadables.downloadable'),
        ),
        migrations.AddField(
            model_name='submissionresponse',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='submissions.submissionrequirement'),
        ),
        migrations.AddField(
            model_name='submissionresponse',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_submission_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
