# Generated by Django 5.2.6 on 2025-11-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadables', '0003_alter_downloadable_options_and_more'),
        ('projects', '0003_alter_projectevent_status_and_more'),
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-deadline'], name='sub_status_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-deadline'], name='sub_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project', 'status'], name='sub_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['downloadable', 'status'], name='sub_form_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project', '-created_at'], name='sub_project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at', 'status'], name='sub_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'event'], name='sub_status_event_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['is_late_submission', 'status'], name='sub_late_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'reviewed_at'], name='sub_review_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionupdate',
            index=models.Index(fields=['user', 'viewed', '-updated_at'], name='subupd_user_view_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionupdate',
            index=models.Index(fields=['submission', '-updated_at'], name='subupd_sub_date_idx'),
        ),
    ]
