# Generated by Django 5.2.6 on 2025-10-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted to College Coordinator'), ('REVISION_REQUESTED', 'Revision Requested'), ('FORWARDED', 'Forwarded to UESO'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=32),
        ),
    ]
