# Generated by Django 5.2.6 on 2025-11-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_submission_image_event_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='image_event',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/event_images/'),
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
