# Generated by Django 5.2.6 on 2025-10-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='rejection_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
