from django import forms
from system.users.models import College
from shared.projects.models import SustainableDevelopmentGoal
from .models import SystemSetting
from rest_framework_api_key.models import APIKey

class CollegeForm(forms.ModelForm):
    class Meta:
        model = College
        fields = ['name', 'campus', 'logo']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'campus': forms.Select(attrs={'class': 'form-select'}),
            'logo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

class SDGForm(forms.ModelForm):
    class Meta:
        model = SustainableDevelopmentGoal
        # Corrected fields based on your models.py
        fields = ['goal_number', 'name']
        widgets = {
            'goal_number': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'e.g., 1'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g., No Poverty'}),
        }

class SystemSettingForm(forms.ModelForm):
    class Meta:
        model = SystemSetting
        fields = ['value']
        widgets = {
            'value': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
class DeleteAccountForm(forms.Form):
    password = forms.CharField(
        label="Confirm your password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password to confirm'})
    )

class APIKeyForm(forms.ModelForm):
    """
    A form for creating the API Key. We only ask for the name.
    The key itself will be generated by the view.
    """
    class Meta:
        model = APIKey
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g., Partner University SIS'}),
        }
