"""
Django settings for WBPMISUESO project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vhc+n8g#3qm1g68newd^ryqd(zj(mx(m!g3b5v8%aaven!ag*$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.137.1', '127.0.0.1', '192.168.254.125', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # External Apps
    'external.home',            # Home

    # Internal Apps
    'internal.agenda',          # Agenda
    'internal.analytics',       # Analytics
    'internal.dashboard',       # Dashboard
    'internal.experts',         # Experts
    'internal.goals',           # Goals
    'internal.submissions',     # Submissions

    # Shared Apps
    'shared.about_us',          # About Us
    'shared.announcements',     # Announcements
    'shared.archive',           # Archive
    'shared.budget',            # Budget
    'shared.event_calendar',    # Calendar
    'shared.downloadables',     # Downloadables
    'shared.projects',          # Projects
    'shared.request',           # Request

    # System Apps
    'system.exports',           # Exports
    'system.logs',              # Logs
    'system.users',             # Custom User
    'system.notifications',     # Notifications
    'system.settings',          # Settings
    'system.scheduler',         # Centralized Scheduler
    'rest_framework',           # Django REST Framework
    'rest_framework_api_key',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'system.users.middleware.SessionSecurityMiddleware',
    'system.users.middleware.RoleBasedSessionMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

ROOT_URLCONF = 'WBPMISUESO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'system.notifications.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'WBPMISUESO.wsgi.application'


# Database

# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# For production (PostgreSQL):
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'ueso',                 # Database Name
#         'USER': 'postgres',             # Username
#         'PASSWORD': 'postgres',         # Password
#         'HOST': 'localhost',            # Server Host
#         'PORT': '5432',                 # Server Port
#     }
# }

# For development/testing (SQLite):
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Custom authentication backend to allow email login
AUTHENTICATION_BACKENDS = [
    'system.users.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (User Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'


# Email settings for local testing
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production, configure SMTP settings as below
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'bab.bmkhn@gmail.com'
EMAIL_HOST_PASSWORD = 'rkwk islz dvlo mqrx'
DEFAULT_FROM_EMAIL = 'bab.bmkhn@gmail.com'

# Site URL for email links (update for production)
SITE_URL = 'http://localhost:8000'


# ============================================================
# SESSION CONFIGURATION
# ============================================================

SESSION_COOKIE_AGE = 86400                      # 24 hours (1 day)
SESSION_SAVE_EVERY_REQUEST = True               # Reset timeout on each activity (sliding window)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False         # Persist across browser restarts (for "Remember Me")

# Session engine (database-backed for persistence)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# ============================================================
# SECURITY SETTINGS
# ============================================================

# Cookie Security
SESSION_COOKIE_SECURE = False                   # DEVELOPMENT: False | PRODUCTION: True (requires HTTPS)
SESSION_COOKIE_HTTPONLY = True                  # Prevent JavaScript access (XSS protection)
SESSION_COOKIE_SAMESITE = 'Lax'                 # CSRF protection (Strict/Lax/None)
SESSION_COOKIE_NAME = 'wbpmisueso_sessionid'    # Custom name (security through obscurity)

# CSRF Protection
CSRF_COOKIE_SECURE = False                      # DEVELOPMENT: False | PRODUCTION: True (requires HTTPS)
CSRF_COOKIE_HTTPONLY = False                    # Allow JavaScript access for AJAX requests
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = 'csrftoken'                  # Standard name for easier access

# Security Headers
SECURE_BROWSER_XSS_FILTER = True                # Enable XSS protection
X_FRAME_OPTIONS = 'DENY'                        # Prevent clickjacking (iframe embedding)
SECURE_CONTENT_TYPE_NOSNIFF = True              # Prevent MIME-sniffing

# HTTPS Settings (enable in production)
# SECURE_SSL_REDIRECT = True                    # Redirect all HTTP to HTTPS
# SECURE_HSTS_SECONDS = 31536000                # HTTP Strict Transport Security (1 year)
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Password Requirements
PASSWORD_RESET_TIMEOUT = 3600                   # Password reset link valid for 1 hour

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'