# Generated by Django 5.2.6 on 2025-09-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to='about_us/hero/')),
                ('vision_text', models.TextField()),
                ('mission_text', models.TextField()),
                ('thrust_text', models.TextField()),
                ('leadership_description', models.TextField(blank=True)),
                ('director_name', models.CharField(max_length=255)),
                ('director_image', models.ImageField(blank=True, null=True, upload_to='about_us/director/')),
                ('org_chart_image', models.ImageField(blank=True, null=True, upload_to='about_us/org_chart/')),
                ('org_chart_description', models.TextField(blank=True)),
            ],
        ),
    ]
