# Generated by Django 5.2.6 on 2025-10-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text', models.TextField(default='Hero Text')),
                ('vision_text', models.TextField(default='Vision Text')),
                ('mission_text', models.TextField(default='Mission Text')),
                ('thrust_text', models.TextField(default='Thrust Text')),
                ('leadership_description', models.TextField(default='Leadership Description')),
                ('director_name', models.CharField(blank=True, default='Director Name', max_length=255, null=True)),
                ('director_image', models.ImageField(blank=True, default=None, null=True, upload_to='about_us/director/')),
                ('org_chart_image', models.ImageField(blank=True, default=None, null=True, upload_to='about_us/org_chart/')),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
