# Generated by Django 5.2.6 on 2025-09-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='org_chart_description',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='edited_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='hero_text',
            field=models.TextField(default='Hero Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='director_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='about_us/director/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='director_name',
            field=models.CharField(blank=True, default='Director Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='leadership_description',
            field=models.TextField(default='Leadership Description'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission_text',
            field=models.TextField(default='Mission Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='org_chart_image',
            field=models.ImageField(blank=True, default='about_us/org_chart/default_org_chart.png', null=True, upload_to='about_us/org_chart/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='thrust_text',
            field=models.TextField(default='Thrust Text'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision_text',
            field=models.TextField(default='Vision Text'),
        ),
    ]
