# Generated by Django 5.2.6 on 2025-10-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='director_image',
            field=models.ImageField(blank=True, default='static/image.png', null=True, upload_to='about_us/director/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='director_name',
            field=models.CharField(blank=True, default='Dr. Liezl F. Tangonan', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='hero_text',
            field=models.TextField(default="Welcome to the University Extension Services Office (UESO). We are dedicated to fostering community engagement and extending the university's knowledge and resources to serve society."),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='leadership_description',
            field=models.TextField(default='Our leadership team is committed to excellence in extension services, guided by principles of integrity, innovation, and inclusive development. We work collaboratively to ensure that university resources reach and benefit the wider community.'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission_text',
            field=models.TextField(default='To deliver innovative extension programs and services that address community needs, promote social responsibility, and contribute to nation-building through collaborative partnerships and knowledge sharing.'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='org_chart_image',
            field=models.ImageField(blank=True, default='static/UESO ORG CHART.png', null=True, upload_to='about_us/org_chart/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='thrust_text',
            field=models.TextField(default='Our strategic thrust focuses on community empowerment, sustainable development, technology transfer, and capacity building to create lasting positive impact in the communities we serve.'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision_text',
            field=models.TextField(default='To be a leading center of excellence in university extension services, creating meaningful partnerships between the academe and the community for sustainable development.'),
        ),
    ]
