# Generated by Django 5.2.6 on 2025-10-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='campus',
            field=models.CharField(choices=[('TINIGUIBAN', 'Tiniguiban Campus'), ('EXTERNAL', 'External Campus')], default='TINIGUIBAN', max_length=20),
        ),
    ]
