# Generated by Django 5.2.6 on 2025-11-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='campus',
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['campus'], name='college_campus_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['name'], name='college_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', '-created_at'], name='user_role_created_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_confirmed'], name='user_role_confirmed_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['college', 'role'], name='user_college_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['college', '-created_at'], name='user_college_created_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_expert', 'role'], name='user_expert_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_expert', 'college'], name='user_expert_college_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_confirmed'], name='user_active_conf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_confirmed', 'role'], name='user_conf_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'given_name'], name='user_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_by', '-created_at'], name='user_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'college', 'is_confirmed'], name='user_role_col_conf_idx'),
        ),
    ]
