# Generated by Django 5.2.4 on 2025-09-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_valid_id_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
