# Generated by Django 5.2.4 on 2025-09-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_preferred_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_id',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('UMID', 'UMID'), ('SSS', 'SSS'), ('GSIS', 'GSIS'), ('PRC', 'PRC'), ('OTHERS', 'Others')], max_length=50, null=True),
        ),
    ]
