# Generated by Django 5.2.6 on 2025-10-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_initial"),
        ("goals", "0002_initial"),
        ("projects", "0003_add_used_budget_if_missing"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="agenda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goals",
                to="agenda.agenda",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="project_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="sdg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goals",
                to="projects.sustainabledevelopmentgoal",
            ),
        ),
    ]
