# Generated by Django 5.2.6 on 2025-10-31 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingevent',
            name='participants',
            field=models.ManyToManyField(related_name='meeting_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingevent',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_meeting_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
