# Generated by Django 5.2.6 on 2025-11-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingevent',
            options={'ordering': ['datetime'], 'verbose_name': 'Meeting Event', 'verbose_name_plural': 'Meeting Events'},
        ),
        migrations.AlterField(
            model_name='meetingevent',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['status', 'datetime'], name='meeting_sched_date_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['datetime'], name='meeting_datetime_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['-created_at'], name='meeting_created_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['created_by', '-created_at'], name='meeting_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['status', '-datetime'], name='meeting_status_idx'),
        ),
    ]
