# Generated by Django 5.2.6 on 2025-11-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingevent',
            name='notes_attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment for meeting notes', null=True, upload_to='meeting_attachments/'),
        ),
    ]
