# Generated by Django 5.2.4 on 2025-10-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='querystring',
            field=models.TextField(blank=True, default=''),
        ),
    ]
