# Generated by Django 5.2.6 on 2025-11-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportrequest',
            options={'ordering': ['-date_submitted'], 'verbose_name': 'Export Request', 'verbose_name_plural': 'Export Requests'},
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['status', '-date_submitted'], name='exp_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['submitted_by', '-date_submitted'], name='exp_submitter_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['type', 'status'], name='exp_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['status', 'reviewed_by'], name='exp_review_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['date_submitted'], name='exp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exportrequest',
            index=models.Index(fields=['status', 'submitted_by'], name='exp_download_ready_idx'),
        ),
    ]
