# Generated by Django 5.2.4 on 2025-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downloadable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='downloadables/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='downloadables/thumbnails/')),
                ('available_for_non_users', models.BooleanField(default=False, help_text='Available for non-logged-in users')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('archived', 'Archived')], default='published', max_length=16)),
                ('file_type', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
