# Generated by Django 5.2.4 on 2025-09-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='available_for_non_users',
            field=models.BooleanField(default=False, help_text='Available for non-logged-in users'),
        ),
    ]
