# Generated by Django 5.2.4 on 2025-10-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadables', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='is_submission_template',
            field=models.BooleanField(default=False, help_text='Used as a template for user submissions'),
        ),
        migrations.AddField(
            model_name='downloadable',
            name='submission_type',
            field=models.CharField(choices=[('event', 'Event'), ('final', 'Final'), ('file', 'File')], default='file', max_length=10),
        ),
    ]
