# Generated by Django 5.2.4 on 2025-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadables', '0003_downloadable_uploaded_at_downloadable_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('archived', 'Archived')], default='published', max_length=16),
        ),
    ]
