# Generated by Django 5.2.4 on 2025-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadables', '0004_downloadable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
