# Generated by Django 5.2.4 on 2025-09-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadables', '0005_downloadable_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='downloadables/thumbnails/'),
        ),
    ]
