# Generated by Django 5.2.6 on 2025-11-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log Entry', 'verbose_name_plural': 'Log Entries'},
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['-timestamp'], name='log_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['user', '-timestamp'], name='log_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['action', '-timestamp'], name='log_action_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['model', '-timestamp'], name='log_model_time_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['model', 'action', '-timestamp'], name='log_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['is_notification', 'timestamp'], name='log_notif_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['model', 'object_id'], name='log_object_idx'),
        ),
    ]
