# Generated by Django 5.2.4 on 2025-09-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='shared/announcements/saved/covers/'),
        ),
    ]
