# Generated by Django 5.2.4 on 2025-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
