# Generated by Django 5.2.6 on 2025-10-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='cover_photo',
            field=models.ImageField(blank=True, default='default/announcements.png', null=True, upload_to='announcements/'),
        ),
    ]
