# Generated by Django 5.2.6 on 2025-11-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-published_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_scheduled', 'scheduled_at', 'published_at'], name='ann_scheduler_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['published_at', 'archived'], name='ann_published_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['archived', '-published_at'], name='ann_active_list_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['title'], name='ann_title_search_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['published_at'], name='ann_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['published_by', '-published_at'], name='ann_publisher_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['published_at', '-scheduled_at'], name='ann_draft_idx'),
        ),
    ]
