# Generated by Django 5.2.4 on 2025-09-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_scheduled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
