# Generated by Django 5.2.4 on 2025-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_announcement_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
