# Generated by Django 5.2.6 on 2025-10-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='concerned_colleges',
            field=models.ManyToManyField(related_name='agendas', to='users.college'),
        ),
    ]
