# Generated by Django 5.2.6 on 2025-11-02 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['-created_at'], name='agenda_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['created_by', '-created_at'], name='agenda_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['name'], name='agenda_name_idx'),
        ),
    ]
